[snow]
# Some particles may not work, the only stable ones I've tested so far are: fireworks_spark, dolphin, flame,totem,damage_indicator,
# There's also 'sweep_attack' that creates a really cool "wind" effect near to the player!
#Choose snow particle, WARNING: MUST BE INSIDE THIS LIST! https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
particle = 'SPIT'
#the radius of snow spawn range
range = 10.00
#the speed of snow (leave it low)
speed = 0.001
#the amount of particles to be spawned
amount = 15
#how often should a particle be spawned (in seconds)
spawnrate = 0.60

[snow.mechanics]
# do not spawn snow when it's raining.
snow-when-raining = false
# Only spawn snow if player is outside (snow will stop spawning if he's inside houses or caves, etc).
snow-only-outside = true

[snow.mechanics.worlds]
# When this is set on true, the plugin will only enable slow on the worlds that have been listed.
specify-enabled-worlds = false
# The worlds where snow should be enabled by default.
enabled-worlds = ["world", "world_the_end"]

[snow.mechanics.underground]
# Only spawn snow if Player is above Y value set below
snow-above-y = false
# The Y axis minimum height for snow to spawn.
y-level = 62
